name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-package-json-v1-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-package-json-v1-

      - name: Set up Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run the lint
        run: npm run lint

      - name: Build Production
        run: npm run build:production